package com.bluntsoftware.app.modules.sensei.repository;

import com.bluntsoftware.app.modules.sensei.domain.Karateclass;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Karateclass.
* @author autogenerated
*/

@Repository("senseiKarateclassRepository")
@Qualifier("sensei")
//@RepositoryRestResource(collectionResourceRel="sensei.Karateclass", path="sensei/Karateclass")
public interface KarateclassRepository extends GenericRepository<Karateclass,Integer>  {

}