package com.bluntsoftware.app.modules.sensei.repository;

import com.bluntsoftware.app.modules.sensei.domain.School;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: School.
* @author autogenerated
*/

@Repository("senseiSchoolRepository")
@Qualifier("sensei")
//@RepositoryRestResource(collectionResourceRel="sensei.School", path="sensei/School")
public interface SchoolRepository extends GenericRepository<School,Integer>  {

}