package com.bluntsoftware.app.modules.sensei.repository;

import com.bluntsoftware.app.modules.sensei.domain.Student;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Student.
* @author autogenerated
*/

@Repository("senseiStudentRepository")
@Qualifier("sensei")
//@RepositoryRestResource(collectionResourceRel="sensei.Student", path="sensei/Student")
public interface StudentRepository extends GenericRepository<Student,Integer>  {

}